#!/usr/bin/env bash
# tagent — AI agent orchestration harness
# Wrapper script: auto-generated by scripts/install-wrapper.sh / make install.
# Loads .env.local from the project root and passes all args to the binary.
# Supports --llm-skills flag (sets TAGENT_SKILL_LLM=1).

set -eo pipefail

TAGENT_PROJECT="__PROJECT_DIR__"
TAGENT_BINARY="${TAGENT_PROJECT}/target/release/tagent"

if [[ ! -x "${TAGENT_BINARY}" ]]; then
  echo "tagent: binary not found at ${TAGENT_BINARY}" >&2
  echo "Run: cd ${TAGENT_PROJECT} && cargo build --release" >&2
  exit 1
fi

# Load API keys from project .env.local if present.
# Parse line-by-line to skip malformed entries gracefully.
if [[ -f "${TAGENT_PROJECT}/.env.local" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    if [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
      export "$line" 2>/dev/null || true
    fi
  done < "${TAGENT_PROJECT}/.env.local"
fi

# Convenience: --llm-skills flag enables LLM-based skill selection
ARGS=()
for arg in "$@"; do
  if [[ "$arg" == "--llm-skills" ]]; then
    export TAGENT_SKILL_LLM=1
  else
    ARGS+=("$arg")
  fi
done

exec "${TAGENT_BINARY}" "${ARGS[@]+"${ARGS[@]}"}"
