# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyMemory < Formula
  desc "trusty-tools: trusty-memory binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.18.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-memory-v0.18.0/trusty-memory-0.18.0-aarch64-apple-darwin.tar.gz"
      sha256 "f886a3404f36891dfd608f48aabbe0a0802c3bebec26a394e19e59e5f4e246a0"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-memory-v0.18.0/trusty-memory-0.18.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7a7eae7b1a0dd3e9e4bceb9a880771c4ecfe6d381796903950042aa42a006ff5"
    end
  end

  def install
    bin.install "trusty-memory"
    bin.install "trusty-bm25-daemon"
  end

  test do
    system bin/"trusty-memory", "--version"
  end
end
