# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyReview < Formula
  desc "trusty-tools: trusty-review binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.16.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.16.0/trusty-review-0.16.0-aarch64-apple-darwin.tar.gz"
      sha256 "0f4bdddcf160688f5df2e5ec5c0893aedd3305e4d715ca4f9a8b4279fa42fc2e"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-review-v0.16.0/trusty-review-0.16.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1c706161ff914f38df694c781af7872f8161903059193458016cf64378bf4ff3"
    end
  end

  def install
    bin.install "trusty-review"
  end

  test do
    system bin/"trusty-review", "--version"
  end
end
