# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustySearch < Formula
  desc "trusty-tools: trusty-search binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.45.1"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.45.1/trusty-search-0.45.1-aarch64-apple-darwin.tar.gz"
      sha256 "3c4849aa35d2fe687899dc5a61248a52e79329f2556e49d362a8e91aae211bc3"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-search-v0.45.1/trusty-search-0.45.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "04fad934635be49142d0cded60a87dd6e4fcf322442298361d27511a719cb7d1"
    end
  end

  def install
    bin.install "trusty-search"
    bin.install "trusty-embedderd"
  end

  test do
    system bin/"trusty-search", "--version"
  end
end
