# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyInstaller < Formula
  desc "trusty-tools: trusty-installer binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.8.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-installer-v0.8.0/trusty-installer-0.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "b7dcb4dbc8a1e1b38e31c99f024a7a32075bc41fbc2e62ff89e1e9fe568d7482"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-installer-v0.8.0/trusty-installer-0.8.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c8c1754fa9f20d0868dc6fcea320d1cf9c180eda977107fdc81a4e180cd9fa0e"
    end
  end

  def install
    bin.install "trusty-installer"
    bin.install "tctl"
  end

  test do
    system bin/"trusty-installer", "--version"
  end
end
