# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyGitAnalytics < Formula
  desc "trusty-tools: trusty-git-analytics binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "2.19.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/tga-v2.19.0/trusty-git-analytics-2.19.0-aarch64-apple-darwin.tar.gz"
      sha256 "4353106dc1429df4a3b0ad8f76fd13ad48a9407533d28e80a6d2464dcd0ed65b"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/tga-v2.19.0/trusty-git-analytics-2.19.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0484ccfa74f36f4a57a2599e201330682be7af5a0bda508ba39ad8d79242a71f"
    end
  end

  def install
    bin.install "tga"
  end

  test do
    system bin/"tga", "--version"
  end
end
