# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyCode < Formula
  desc "trusty-tools: trusty-code binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.2.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-code-v0.2.0/trusty-code-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "62012b5225ee6d7cb33ee745390d03be7c68c49f096bca0ef5105ae2154b107a"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-code-v0.2.0/trusty-code-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "eb7c78393abbb558307533bf3cfdf4373b32ed0a6b5cc9ef8e5e2518910882c5"
    end
  end

  def install
    bin.install "tcode"
  end

  test do
    system bin/"tcode", "--version"
  end
end
