# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyConsole < Formula
  desc "trusty-tools: trusty-console binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "0.4.0"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-console-v0.4.0/trusty-console-0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "e7fa88af9b8aa5d3e02574eaf211c3db3882259f1cfb4c53d371eebabeec8da4"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-console-v0.4.0/trusty-console-0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "13ee73466671f93abf08b98fc632d1527b1f1908a41d8de62e3e2f2024414286"
    end
  end

  def install
    bin.install "trusty-console"
  end

  test do
    system bin/"trusty-console", "--version"
  end
end
