# Generated by the Binary Release workflow (release.yml).
# Do not edit by hand — changes will be overwritten on the next release.
# To customise behaviour, edit .github/workflows/release.yml in
# bobmatnyc/trusty-tools (homebrew-bump job, "Generate or update Formula" step).
class TrustyMpm < Formula
  desc "trusty-tools: trusty-mpm binary"
  homepage "https://github.com/bobmatnyc/trusty-tools"
  version "1.3.6"

  # macOS arm64 (Apple Silicon) pre-built binary
  on_macos do
    on_arm do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-mpm-v1.3.6/trusty-mpm-1.3.6-aarch64-apple-darwin.tar.gz"
      sha256 "216bb08b8381c6a07932c905c7002f098094124673e222a7b968d8f4d8c91dfe"
    end
  end

  # Linux x86_64 (glibc 2.17+) pre-built binary
  on_linux do
    on_intel do
      url "https://github.com/bobmatnyc/trusty-tools/releases/download/trusty-mpm-v1.3.6/trusty-mpm-1.3.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "54964e9b3d8e91655cd516c776ee680e2a05871bfef44a27ef228c6a81a539e1"
    end
  end

  def install
    bin.install "tm"
    bin.install "trusty-mpm"
  end

  test do
    system bin/"tm", "--version"
  end
end
