//! Built-in skills for the filesystem, shell, git, AST and analysis tools.
//!
//! Why: These are the in-process tools every coding-tier agent registers
//! (`runtime/tool_registry::build_registry_for_agent`). Each gets one named
//! skill so the Skills pane can describe what an agent may do in prose the user
//! reads, rather than echoing `grep_files` back at them.
//! What: A `const` table of one-tool [`SkillDef`] rows. File split is size-only
//! — see the module doc of `builtin/mod.rs`.
//! Test: `super::super::tests::every_tool_declared_in_source_has_a_skill`.

use super::super::{SkillDef, SkillKind::Action, SkillKind::System, tool_skill};

pub(super) static TABLE: &[SkillDef] = &[
    // --- filesystem ------------------------------------------------------
    tool_skill(
        "file-read",
        "Read a File",
        "Read a file's contents from disk.",
        "read_file",
        Action,
        None,
    ),
    tool_skill(
        "file-write",
        "Write a File",
        "Create or overwrite a file on disk.",
        "write_file",
        Action,
        None,
    ),
    tool_skill(
        "dir-list",
        "List a Directory",
        "List the entries of a directory on disk.",
        "list_dir",
        Action,
        None,
    ),
    tool_skill(
        "file-grep",
        "Search File Contents",
        "Find lines matching a pattern across files on disk.",
        "grep_files",
        Action,
        None,
    ),
    tool_skill(
        "file-move",
        "Move or Rename a File",
        "Move or rename a file or directory on disk.",
        "move_file",
        Action,
        None,
    ),
    tool_skill(
        "dir-create",
        "Create a Directory",
        "Create a directory, including any missing parents.",
        "create_dir",
        Action,
        None,
    ),
    // --- shell -----------------------------------------------------------
    tool_skill(
        "shell-run",
        "Run a Shell Command",
        "Run a shell command in the working directory and return its output.",
        "run_bash",
        Action,
        None,
    ),
    tool_skill(
        "shell-exec",
        "Execute a Sandboxed Command",
        "Execute a command through the workflow-agent shell sandbox.",
        "shell_exec",
        Action,
        None,
    ),
    tool_skill(
        "pytest-run",
        "Run Python Tests",
        "Run a pytest selection and report the results.",
        "pytest_exec",
        Action,
        None,
    ),
    // --- git inspection --------------------------------------------------
    tool_skill(
        "git-status",
        "Git Working Tree Status",
        "Report staged, unstaged and untracked changes in the repository.",
        "git_status",
        Action,
        None,
    ),
    tool_skill(
        "git-history",
        "Git Commit History",
        "Read recent commits with author, date and subject.",
        "git_log",
        Action,
        None,
    ),
    tool_skill(
        "git-commit-search",
        "Search Git History",
        "Find commits whose message or content matches a query.",
        "git_search_commits",
        Action,
        None,
    ),
    tool_skill(
        "git-branch-list",
        "List Git Branches",
        "List the repository's local and remote branches.",
        "git_branches",
        Action,
        None,
    ),
    // --- git mutation ----------------------------------------------------
    tool_skill(
        "git-branch-create",
        "Create a Git Branch",
        "Create a new branch in the repository.",
        "git_create_branch",
        Action,
        None,
    ),
    tool_skill(
        "git-checkout",
        "Switch Git Branch",
        "Check out an existing branch or revision.",
        "git_checkout",
        Action,
        None,
    ),
    tool_skill(
        "git-stage",
        "Stage Git Changes",
        "Stage files for the next commit.",
        "git_stage",
        Action,
        None,
    ),
    tool_skill(
        "git-commit",
        "Commit Git Changes",
        "Record the staged changes as a commit.",
        "git_commit",
        Action,
        None,
    ),
    tool_skill(
        "git-stash",
        "Stash Git Changes",
        "Shelve uncommitted changes for later.",
        "git_stash",
        Action,
        None,
    ),
    tool_skill(
        "git-push",
        "Push to a Git Remote",
        "Publish local commits to a remote branch.",
        "git_push",
        Action,
        None,
    ),
    tool_skill(
        "git-pull",
        "Pull from a Git Remote",
        "Fetch and integrate remote commits into the current branch.",
        "git_pull",
        Action,
        None,
    ),
    tool_skill(
        "git-fetch",
        "Fetch from a Git Remote",
        "Download remote refs without changing the working tree.",
        "git_fetch",
        Action,
        None,
    ),
    // --- AST editing -----------------------------------------------------
    tool_skill(
        "code-symbol-read",
        "Read a Code Symbol",
        "Fetch one function, class or symbol by name from a source file.",
        "get_symbol",
        Action,
        None,
    ),
    tool_skill(
        "code-symbol-edit",
        "Edit a Code Symbol",
        "Replace the body of a named function, class or symbol.",
        "edit_symbol",
        Action,
        None,
    ),
    tool_skill(
        "code-symbol-insert",
        "Insert a Code Symbol",
        "Insert a new function, class or symbol into a source file.",
        "insert_symbol",
        Action,
        None,
    ),
    tool_skill(
        "code-patch",
        "Apply a Code Patch",
        "Apply a unified diff to the working tree.",
        "apply_patch",
        Action,
        None,
    ),
    tool_skill(
        "code-import-add",
        "Add a Code Import",
        "Add an import or use statement to a source file.",
        "add_import",
        Action,
        None,
    ),
    tool_skill(
        "code-syntax-check",
        "Check Code Syntax",
        "Parse a source file and report syntax errors.",
        "validate_syntax",
        Action,
        None,
    ),
    // --- static analysis -------------------------------------------------
    tool_skill(
        "analysis-file",
        "Analyse a Source File",
        "Report structure, complexity and metrics for one source file.",
        "analyze_file",
        Action,
        None,
    ),
    tool_skill(
        "analysis-project",
        "Analyse a Project",
        "Report structure, language mix and metrics across a whole project.",
        "analyze_project",
        Action,
        None,
    ),
    tool_skill(
        "analysis-hotspots",
        "Find Complexity Hotspots",
        "Rank the most complex functions and files in a project.",
        "get_complexity_hotspots",
        Action,
        None,
    ),
    tool_skill(
        "analysis-smells",
        "Find Code Smells",
        "Report duplicated, over-long or otherwise suspect code.",
        "find_smells",
        Action,
        None,
    ),
    tool_skill(
        "analysis-cycles",
        "Find Circular Dependencies",
        "Detect import or module cycles in a project.",
        "check_circular_dependencies",
        Action,
        None,
    ),
    tool_skill(
        "analysis-call-flow",
        "Trace Execution Flow",
        "Follow a call chain from an entry point through the codebase.",
        "trace_execution_flow",
        Action,
        None,
    ),
    // --- timers ----------------------------------------------------------
    tool_skill(
        "wait-fixed",
        "Wait a Fixed Delay",
        "Pause for a fixed number of milliseconds.",
        "wait_ms",
        System,
        None,
    ),
    tool_skill(
        "wait-condition",
        "Wait for a Condition",
        "Poll until a condition holds or a deadline passes.",
        "poll_until",
        System,
        None,
    ),
];
