//! Schema profile — OKF v0.1 container + snake_case schema.org/FOAF relations.
//!
//! Why: the KB store's structure is pluggable so the researched schema can
//! replace this one file without touching store/convert/validate logic. This is
//! that researched profile: the Open Knowledge Format (OKF) v0.1 container
//! (GoogleCloudPlatform/knowledge-catalog, okf/SPEC.md) with a snake_case
//! schema.org/FOAF relationship profile layered on top.
//!
//! What (OKF v0.1 container rules, enforced across the crate):
//!   - `type` is the ONLY required frontmatter field; every other field is
//!     optional and is never invented for a missing value.
//!   - `index.md` and `log.md` are RESERVED filenames carrying NO frontmatter:
//!     they are not entities. `index.md` IS the per-folder README (generated by
//!     [`crate::structure`]); `log.md` is an optional append-only change log.
//!   - Unknown frontmatter keys are preserved verbatim (merge, never strip) —
//!     enforced in [`crate::entity`]'s deep-merge and every render path.
//!
//! What (profile on top of the container):
//!   - Folder-per-type collections, each mapped to a schema.org type where one
//!     exists (see [`CollectionSpec::schema_type`]).
//!   - A shared base envelope: `type` (required), `title`, `aliases[]`,
//!     `description`, `tags[]`, `uid` (stable rename-safe id), `same_as[]`
//!     (external authority URIs — the entity-resolution/dedup key), `sources[]`
//!     (provenance, distinct from `same_as`), `created`/`updated` (ISO-8601;
//!     `updated` changes only on real content change).
//!   - snake_case relationship fields holding `[[wiki-links]]` (quoted scalar or
//!     list), per collection (see [`CollectionSpec::edge_fields`]).
//!
//! Inverse-edge reconciler ([`EDGE_PAIRS`] / [`inverse_edge`]): writing one side
//! of a relation materialises the other deterministically (see
//! [`crate::reconcile`]). Bidirectional pairs: parent_of↔child_of,
//! works_at↔employee, member_of↔member, parent_org↔sub_org,
//! located_in↔contains, mentor_of↔apprentice_to. Symmetric verbs (mirror the
//! same verb on the target): knows, sibling_of, spouse_of, colleague_of,
//! family_of, neighbor_of.
//!
//! schema.org / FOAF export mapping (DOCUMENTED, not built — a future JSON-LD
//! exporter would consume it): title→schema:name/foaf:name, aliases→schema:
//! alternateName, description→schema:description, same_as→schema:sameAs,
//! knows→foaf:knows, works_at→schema:worksFor, member_of→schema:memberOf,
//! located_in→schema:containedInPlace (inverse schema:containsPlace),
//! parent_of→schema:parent (inverse schema:children), spouse_of→schema:spouse,
//! founder→schema:founder, organizer→schema:organizer, attendee→schema:
//! attendee, about→schema:about, creator→schema:creator, owner→schema:owner.
//! JSON-LD frontmatter, PARA/Johnny-Decimal, Dendron schema.yml, Dataview
//! inline fields, RDF serialisation, and the LogSeq block model are explicitly
//! NOT adopted.
//!
//! Test: `default_profile_has_core_collections`, `type_is_only_required_field`,
//! `edge_inverses_are_symmetric`, `reserved_files_are_not_entities`.

/// Reserved OKF filenames that are NOT entities and carry no frontmatter.
///
/// `index.md` is the generated per-folder README; `log.md` is the optional
/// append-only change log. Listing, validation, and conversion all skip these.
pub const RESERVED_FILES: [&str; 2] = ["index.md", "log.md"];

/// Whether a filename is an OKF reserved (non-entity) file.
///
/// Test: `reserved_files_are_not_entities`.
pub fn is_reserved_file(file_name: &str) -> bool {
    RESERVED_FILES.contains(&file_name)
}

/// The value-type a base-envelope field is expected to hold. Relationship (edge)
/// fields are validated structurally via [`inverse_edge`], not listed here.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    /// A single scalar string (e.g. `title`, `uid`).
    Scalar,
    /// A YAML sequence of scalars (e.g. `aliases`, `same_as`, `sources`).
    List,
    /// An ISO-8601 date/time scalar (e.g. `created`, `updated`).
    Date,
}

/// One base-envelope field specification.
#[derive(Debug, Clone)]
pub struct FieldSpec {
    /// The frontmatter key.
    pub name: &'static str,
    /// The value shape expected for this key.
    pub ty: FieldType,
    /// When true, validation reports the entity if the key is absent. Under OKF
    /// v0.1 this is set only for `type`.
    pub required: bool,
}

impl FieldSpec {
    const fn new(name: &'static str, ty: FieldType, required: bool) -> Self {
        Self { name, ty, required }
    }
}

/// One collection: a top-level directory holding entities of a kind.
#[derive(Debug, Clone)]
pub struct CollectionSpec {
    /// Directory name under the KB root (e.g. `people`).
    pub name: &'static str,
    /// The schema.org type new entities default their `type` to, if any.
    /// `None` for `projects` (OKF uses a free `type` string there).
    pub schema_type: Option<&'static str>,
    /// One-line purpose, surfaced in the generated `index.md`.
    pub purpose: &'static str,
    /// snake_case relationship field names valid for this collection (for docs
    /// and README generation). Reconciliation itself is driven by the global
    /// [`inverse_edge`] map, not this list.
    pub edge_fields: &'static [&'static str],
}

/// The shared OKF base-envelope field set (identical across collections).
///
/// Why: OKF's container is uniform — the collection only changes the default
/// `type` and which relationship verbs are idiomatic. Keeping one envelope list
/// avoids per-collection drift.
/// What: `type` required; everything else optional.
/// Test: `type_is_only_required_field`.
pub fn base_envelope() -> Vec<FieldSpec> {
    vec![
        FieldSpec::new("type", FieldType::Scalar, true),
        FieldSpec::new("title", FieldType::Scalar, false),
        FieldSpec::new("aliases", FieldType::List, false),
        FieldSpec::new("description", FieldType::Scalar, false),
        FieldSpec::new("tags", FieldType::List, false),
        FieldSpec::new("uid", FieldType::Scalar, false),
        FieldSpec::new("same_as", FieldType::List, false),
        FieldSpec::new("sources", FieldType::List, false),
        FieldSpec::new("created", FieldType::Date, false),
        FieldSpec::new("updated", FieldType::Date, false),
    ]
}

/// Bidirectional + symmetric edge pairs `(forward, inverse)`.
///
/// Symmetric verbs appear as `(verb, verb)`. The inverse relation is
/// materialised on the link target by [`crate::reconcile`]. This is the single
/// source of truth for "which frontmatter keys are relationship edges".
pub const EDGE_PAIRS: &[(&str, &str)] = &[
    // Bidirectional
    ("parent_of", "child_of"),
    ("child_of", "parent_of"),
    ("works_at", "employee"),
    ("employee", "works_at"),
    ("member_of", "member"),
    ("member", "member_of"),
    ("parent_org", "sub_org"),
    ("sub_org", "parent_org"),
    ("located_in", "contains"),
    ("contains", "located_in"),
    ("mentor_of", "apprentice_to"),
    ("apprentice_to", "mentor_of"),
    // Symmetric (mirror the same verb on the target)
    ("knows", "knows"),
    ("sibling_of", "sibling_of"),
    ("spouse_of", "spouse_of"),
    ("colleague_of", "colleague_of"),
    ("family_of", "family_of"),
    ("neighbor_of", "neighbor_of"),
];

/// The inverse relationship name for an edge field, if it is a known edge.
///
/// Why: the reconciler and typed-edge extraction both need "is this key a
/// relationship, and what mirrors it?" from one table.
/// What: `Some(inverse)` for any key in [`EDGE_PAIRS`] (a symmetric verb maps to
/// itself), `None` for a non-edge key.
/// Test: `edge_inverses_are_symmetric`.
pub fn inverse_edge(field: &str) -> Option<&'static str> {
    EDGE_PAIRS
        .iter()
        .find(|(f, _)| *f == field)
        .map(|(_, inv)| *inv)
}

/// The active schema profile: the set of known collections.
#[derive(Debug, Clone)]
pub struct Profile {
    /// Known collections, in the deterministic order they are created/rendered.
    pub collections: Vec<CollectionSpec>,
}

impl Profile {
    /// The default OKF v0.1 + schema.org/FOAF profile.
    ///
    /// Why: the shipped baseline; a different research outcome replaces this fn.
    /// What: the six folder-per-type collections with their schema.org types and
    /// idiomatic relationship verbs.
    /// Test: `default_profile_has_core_collections`.
    pub fn default_profile() -> Self {
        const PERSON: &[&str] = &[
            "knows",
            "works_at",
            "member_of",
            "colleague_of",
            "spouse_of",
            "parent_of",
            "child_of",
            "sibling_of",
            "family_of",
            "mentor_of",
            "located_in",
        ];
        const ORG: &[&str] = &[
            "member",
            "employee",
            "founder",
            "parent_org",
            "sub_org",
            "located_in",
        ];
        const PLACE: &[&str] = &["located_in", "contains"];
        const EVENT: &[&str] = &["location", "organizer", "attendee", "about"];
        const PROJECT: &[&str] = &["member", "sponsor", "located_in", "related_to"];
        const THING: &[&str] = &["creator", "owner", "located_in", "about"];
        Self {
            collections: vec![
                CollectionSpec {
                    name: "people",
                    schema_type: Some("Person"),
                    purpose: "Individual people the assistant tracks.",
                    edge_fields: PERSON,
                },
                CollectionSpec {
                    name: "organizations",
                    schema_type: Some("Organization"),
                    purpose: "Companies, teams, and institutions.",
                    edge_fields: ORG,
                },
                CollectionSpec {
                    name: "places",
                    schema_type: Some("Place"),
                    purpose: "Locations, venues, and geographic entities.",
                    edge_fields: PLACE,
                },
                CollectionSpec {
                    name: "events",
                    schema_type: Some("Event"),
                    purpose: "Meetings, milestones, and dated occurrences.",
                    edge_fields: EVENT,
                },
                CollectionSpec {
                    name: "projects",
                    schema_type: None,
                    purpose: "Ongoing efforts and initiatives.",
                    edge_fields: PROJECT,
                },
                CollectionSpec {
                    name: "things",
                    schema_type: Some("Thing"),
                    purpose: "Objects, products, concepts, and everything else.",
                    edge_fields: THING,
                },
            ],
        }
    }

    /// Look up a collection spec by directory name.
    ///
    /// Test: `default_profile_has_core_collections`.
    pub fn collection(&self, name: &str) -> Option<&CollectionSpec> {
        self.collections.iter().find(|c| c.name == name)
    }

    /// Whether `name` is one of the profile's known collections.
    ///
    /// Test: `default_profile_has_core_collections`.
    pub fn is_known_collection(&self, name: &str) -> bool {
        self.collection(name).is_some()
    }

    /// The known collection directory names, in profile order.
    pub fn collection_names(&self) -> Vec<&'static str> {
        self.collections.iter().map(|c| c.name).collect()
    }

    /// The default `type` value for a new entity created in `collection`.
    ///
    /// Why: OKF requires `type`; when a caller omits it, the collection's
    /// schema.org type is the honest default (never a guessed value).
    /// What: the collection's `schema_type` if known, else `Note` (the
    /// container-level fail-open type for a free/unknown collection).
    /// Test: `default_type_for_collection_falls_back_to_note`.
    pub fn default_type_for(&self, collection: &str) -> String {
        self.collection(collection)
            .and_then(|c| c.schema_type)
            .unwrap_or("Note")
            .to_string()
    }
}

impl Default for Profile {
    fn default() -> Self {
        Self::default_profile()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Why: the six folder-per-type collections are the baseline contract.
    /// What: asserts the collection set, order, and a schema.org type mapping.
    /// Test: self-contained.
    #[test]
    fn default_profile_has_core_collections() {
        let p = Profile::default_profile();
        assert_eq!(
            p.collection_names(),
            vec![
                "people",
                "organizations",
                "places",
                "events",
                "projects",
                "things"
            ]
        );
        assert_eq!(p.collection("people").unwrap().schema_type, Some("Person"));
        assert_eq!(p.collection("projects").unwrap().schema_type, None);
        assert!(p.is_known_collection("things"));
        assert!(!p.is_known_collection("recipes"));
    }

    /// Why: OKF v0.1's defining rule is that `type` is the ONLY required field.
    /// What: asserts exactly one envelope field is required, and it is `type`.
    /// Test: self-contained.
    #[test]
    fn type_is_only_required_field() {
        let required: Vec<&str> = base_envelope()
            .into_iter()
            .filter(|f| f.required)
            .map(|f| f.name)
            .collect();
        assert_eq!(required, vec!["type"]);
    }

    /// Why: the reconciler depends on the inverse map being an involution —
    /// inverse(inverse(x)) == x — or edges would not reconcile on re-run.
    /// What: asserts every forward edge's inverse maps back to it.
    /// Test: self-contained.
    #[test]
    fn edge_inverses_are_symmetric() {
        for (forward, inverse) in EDGE_PAIRS {
            let back = inverse_edge(inverse).expect("inverse must itself be an edge");
            assert_eq!(back, *forward, "inverse of {inverse} should be {forward}");
        }
        assert_eq!(inverse_edge("knows"), Some("knows"));
        assert_eq!(inverse_edge("parent_of"), Some("child_of"));
        assert_eq!(inverse_edge("not_an_edge"), None);
    }

    /// Why: reserved files must never be treated as entities.
    /// What: asserts index.md/log.md are reserved and a normal file is not.
    /// Test: self-contained.
    #[test]
    fn reserved_files_are_not_entities() {
        assert!(is_reserved_file("index.md"));
        assert!(is_reserved_file("log.md"));
        assert!(!is_reserved_file("ada-lovelace.md"));
    }

    /// Why: OKF fail-open — an unknown collection still yields a valid `type`.
    /// What: asserts `Note` fallback for a free collection.
    /// Test: self-contained.
    #[test]
    fn default_type_for_collection_falls_back_to_note() {
        let p = Profile::default_profile();
        assert_eq!(p.default_type_for("people"), "Person");
        assert_eq!(p.default_type_for("recipes"), "Note");
    }
}
