//! `kb_ensure_structure` — idempotent collection dirs + generated `index.md`.
//!
//! Why: OKF makes `index.md` the per-folder README (a GENERATED artifact, not a
//! hand-edited file). Regeneration must be deterministic so a re-run is a no-op
//! and the convert idempotency guarantee holds. The "updated" line therefore
//! derives from the newest entity timestamp in the folder — content-derived, not
//! wall-clock — so identical content always yields byte-identical READMEs.
//!
//! What: [`KbStore::ensure_structure`] creates every known collection directory,
//! then (re)generates `index.md` for every collection present on disk (known +
//! free topic dirs) with a purpose line + a name/summary inventory table, plus a
//! root `index.md` topic map. Files are written only when their content changes.
//!
//! Test: `ensure_creates_known_dirs`, `index_regeneration_is_deterministic`,
//! `root_index_lists_collections`.

use serde::Serialize;

use crate::store::{KbStore, summarise};

/// Generated-file marker: the first line of every `index.md` this tool writes.
pub const GENERATED_MARKER: &str =
    "<!-- GENERATED by trusty-kb; do not edit — regenerate with kb_ensure_structure -->";

/// Result of a `kb_ensure_structure` call.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct EnsureOutcome {
    /// Root-relative collection directories newly created.
    pub created_dirs: Vec<String>,
    /// Root-relative `index.md` paths (re)written this run.
    pub indexes_written: Vec<String>,
    /// Whether the root `index.md` was (re)written.
    pub root_index_written: bool,
}

impl KbStore {
    /// Create collection dirs and (re)generate every `index.md`.
    ///
    /// Why/What/Test: see the module doc.
    pub fn ensure_structure(&self) -> anyhow::Result<EnsureOutcome> {
        std::fs::create_dir_all(&self.root)?;
        let mut created_dirs = Vec::new();
        for name in self.profile.collection_names() {
            let dir = self.collection_dir(name)?;
            if !dir.exists() {
                std::fs::create_dir_all(&dir)?;
                created_dirs.push(name.to_string());
            }
        }

        // Every collection dir present on disk (known + free) gets an index.
        let mut colls = self.collection_dirs_on_disk()?;
        for known in self.profile.collection_names() {
            if !colls.iter().any(|c| c == known) {
                colls.push(known.to_string());
            }
        }
        colls.sort();
        colls.dedup();

        let mut indexes_written = Vec::new();
        for coll in &colls {
            let content = self.render_collection_index(coll)?;
            let path = self.collection_dir(coll)?.join("index.md");
            if self.write_text_if_changed(&path, &content)? {
                indexes_written.push(self.rel(&path));
            }
        }
        indexes_written.sort();

        let root_content = self.render_root_index(&colls)?;
        let root_path = self.root.join("index.md");
        let root_index_written = self.write_text_if_changed(&root_path, &root_content)?;

        Ok(EnsureOutcome {
            created_dirs,
            indexes_written,
            root_index_written,
        })
    }

    /// Write `content` to `path` only if it differs from the current file.
    /// Returns whether the file changed. Creates parent dirs as needed.
    pub fn write_text_if_changed(
        &self,
        path: &std::path::Path,
        content: &str,
    ) -> anyhow::Result<bool> {
        if let Ok(existing) = std::fs::read_to_string(path)
            && existing == content
        {
            return Ok(false);
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)?;
        Ok(true)
    }

    /// Render the `index.md` body for one collection.
    fn render_collection_index(&self, coll: &str) -> anyhow::Result<String> {
        let files = self.entity_files(coll)?;
        let purpose = self
            .profile
            .collection(coll)
            .map(|c| c.purpose.to_string())
            .unwrap_or_else(|| format!("Free topic directory: {coll}."));
        let known = if self.profile.is_known_collection(coll) {
            ""
        } else {
            " (free topic)"
        };

        let mut newest = String::new();
        let mut rows = String::new();
        for (slug, path) in &files {
            let Some(entity) = self.read_entity_at(path)? else {
                continue;
            };
            let title = entity.get_str("title").unwrap_or(slug);
            let summary = summarise(&entity).unwrap_or_default();
            rows.push_str(&format!("| [{title}]({slug}.md) | {summary} |\n"));
            for k in ["updated", "created"] {
                if let Some(ts) = entity.get_str(k)
                    && ts > newest.as_str()
                {
                    newest = ts.to_string();
                }
            }
        }

        let mut out = String::new();
        out.push_str(GENERATED_MARKER);
        out.push_str(&format!(
            "\n\n# {}{}\n\n{}\n\n",
            title_case(coll),
            known,
            purpose
        ));
        out.push_str(&format!(
            "{} entit{}.\n\n",
            files.len(),
            plural(files.len())
        ));
        if files.is_empty() {
            out.push_str("_No entities yet._\n");
        } else {
            out.push_str("| Entity | Summary |\n| --- | --- |\n");
            out.push_str(&rows);
        }
        if !newest.is_empty() {
            out.push_str(&format!("\n_Latest entity update: {newest}_\n"));
        }
        Ok(out)
    }

    /// Render the root `index.md` topic map.
    fn render_root_index(&self, colls: &[String]) -> anyhow::Result<String> {
        let mut out = String::new();
        out.push_str(GENERATED_MARKER);
        out.push_str("\n\n# Knowledge Base\n\nCollections in this tree.\n\n");
        out.push_str("| Collection | Entities | Kind |\n| --- | --- | --- |\n");
        for coll in colls {
            let count = self.entity_files(coll)?.len();
            let kind = if self.profile.is_known_collection(coll) {
                "known"
            } else {
                "free topic"
            };
            out.push_str(&format!(
                "| [{coll}]({coll}/index.md) | {count} | {kind} |\n"
            ));
        }
        Ok(out)
    }
}

/// Capitalise the first character of a collection name.
fn title_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn plural(n: usize) -> &'static str {
    if n == 1 { "y" } else { "ies" }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::put::empty_map;
    use crate::schema::Profile;

    fn store() -> (tempfile::TempDir, KbStore) {
        let tmp = tempfile::tempdir().unwrap();
        let s = KbStore::new(tmp.path().to_path_buf(), Profile::default_profile());
        (tmp, s)
    }

    /// Why: ensure_structure must create the six known dirs + their indexes.
    /// What: runs on an empty root; asserts dirs and index.md files exist and
    /// carry the generated marker.
    /// Test: self-contained.
    #[test]
    fn ensure_creates_known_dirs() {
        let (_t, s) = store();
        let out = s.ensure_structure().unwrap();
        assert_eq!(out.created_dirs.len(), 6);
        assert!(s.root.join("people/index.md").is_file());
        let idx = std::fs::read_to_string(s.root.join("people/index.md")).unwrap();
        assert!(idx.starts_with(GENERATED_MARKER));
        assert!(out.root_index_written);
    }

    /// Why: index regeneration must be deterministic (a no-op on re-run) so the
    /// convert idempotency guarantee holds.
    /// What: adds an entity, ensures twice; asserts the second ensure writes no
    /// index and the file is byte-identical.
    /// Test: self-contained.
    #[test]
    fn index_regeneration_is_deterministic() {
        let (_t, s) = store();
        s.put_entity(
            "people",
            "Ada",
            empty_map(),
            None,
            false,
            "2026-01-01T00:00:00Z",
        )
        .unwrap();
        s.ensure_structure().unwrap();
        let first = std::fs::read_to_string(s.root.join("people/index.md")).unwrap();
        let out = s.ensure_structure().unwrap();
        let second = std::fs::read_to_string(s.root.join("people/index.md")).unwrap();
        assert_eq!(first, second);
        assert!(out.indexes_written.is_empty(), "re-run must be a no-op");
        assert!(first.contains("| [Ada](ada.md) |"));
    }

    /// Why: the root index is the tree topic map.
    /// What: asserts the root index lists collections with counts.
    /// Test: self-contained.
    #[test]
    fn root_index_lists_collections() {
        let (_t, s) = store();
        s.put_entity(
            "people",
            "Ada",
            empty_map(),
            None,
            false,
            "2026-01-01T00:00:00Z",
        )
        .unwrap();
        s.ensure_structure().unwrap();
        let root = std::fs::read_to_string(s.root.join("index.md")).unwrap();
        assert!(root.contains("# Knowledge Base"));
        assert!(root.contains("| [people](people/index.md) | 1 | known |"));
    }
}
