//! Cutting one rendered document into the code-review report and a standalone
//! authorship report (#6046).
//!
//! Why: owner request 2026-08-19 — "I'd like to see the outputs of the code
//! review separate from authorship." Authorship is derived by tga from git
//! history and never reads source, so a diligence reader wants it as its own
//! deliverable rather than a section two thirds of the way down the
//! code-review document.
//! What: [`split_authorship`] removes the Authorship & Key-Person Risk section
//! from a rendered, polished document and hands it back separately;
//! [`authorship_document`] wraps that section as a document with its own title
//! and provenance legend; [`signature_last`] moves the template's closing
//! signature below the sections the render appends after it. All three run
//! inside `Reporter::render_documents`, after
//! `polish` (so the section carries the same dropped-marker and no-data
//! treatment it had inside the one document) and BEFORE
//! `contents_links::inject` (so the code-review report's jump list never links
//! a heading it no longer carries).
//! Test: `split_tests.rs`.

use super::provenance;

/// Text that identifies the authorship section's level-2 heading.
///
/// Why: the bundled template heads it `## Authorship & Key-Person Risk`, but an
/// operator template may number or reword it. Matching one distinctive word
/// keeps a renamed heading splitting instead of silently landing back in the
/// code-review document.
const AUTHORSHIP_HEADING_NEEDLE: &str = "Authorship";

/// Filename suffix the authorship document is written under.
pub const AUTHORSHIP_STEM_SUFFIX: &str = "-authorship";

/// Prefix every authorship-load gap line carries, set in one place by
/// `model.rs`'s fail-open arm (#5453/#6004).
const AUTHORSHIP_GAP_PREFIX: &str = "Authorship (";

/// Text that identifies the first line of the template's closing signature.
///
/// Both bundled templates name the tool and the template id on that line; the
/// tool name alone is the stable half, so an operator template that renames its
/// own version still gets its signature moved.
const SIGNATURE_NEEDLE: &str = "*Generated by trusty-review report analysis";

/// Move the template's closing signature block to the true end of the document.
///
/// Why: the signature sits at the bottom of the TEMPLATE, and `render_documents`
/// appends Synthesis Status, Dependency Inventory and Investigation Coverage
/// after the template is filled. The graded report therefore signed off at line
/// 1883 and carried three more sections after it, so a reader who stopped at the
/// signature — which is what a signature is for — missed the coverage record
/// that qualifies every finding above it.
/// What: finds the signature line, takes the `---` rule and the italic lines
/// that travel with it, cuts the block out, and re-appends it after everything
/// else. A document with no signature line is returned unchanged, and a document
/// whose signature is already last is returned unchanged, so the pass is safe to
/// run on any render.
/// Test: `split_tests::{signature_moves_below_appended_sections,
/// signature_already_last_is_unchanged, no_signature_leaves_the_document_whole}`.
pub fn signature_last(rendered: &str) -> String {
    let lines: Vec<&str> = rendered.lines().collect();
    let Some(at) = lines
        .iter()
        .position(|l| l.trim_start().starts_with(SIGNATURE_NEEDLE))
    else {
        return rendered.to_string();
    };

    // The horizontal rule above the signature belongs to it; blank lines between
    // the two travel with the block so it re-appends exactly as authored.
    let mut start = at;
    let mut above = at;
    while above > 0 && lines[above - 1].trim().is_empty() {
        above -= 1;
    }
    if above > 0 && lines[above - 1].trim() == "---" {
        start = above - 1;
    }
    // The signature is one or more consecutive italic lines.
    let mut end = at;
    while end + 1 < lines.len() && lines[end + 1].trim().starts_with('*') {
        end += 1;
    }

    let block = lines[start..=end].join("\n");
    let mut rest: Vec<&str> = lines[..start].to_vec();
    rest.extend_from_slice(&lines[end + 1..]);
    while rest.last().is_some_and(|l| l.trim().is_empty()) {
        rest.pop();
    }

    let mut out = rest.join("\n");
    out.push_str("\n\n");
    out.push_str(&block);
    if rendered.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Remove the authorship section from a rendered document.
///
/// Why: the split is a post-render cut rather than a second template, so both
/// documents are filled from one scope and cannot drift in wording, provenance
/// tagging, or honesty-marker handling.
/// What: scans level-2 (`## `) headings in document order, tracking fenced code
/// blocks with the same toggle guard [`super::contents_links::inject`] uses so
/// a `## `-prefixed line inside quoted source bytes is never mistaken for a
/// heading. Everything from the authorship heading up to the next level-2
/// heading (or end of document) is returned as the second element; everything
/// else is the first. A document with no authorship heading — a custom template
/// that omits the section — returns `(rendered, None)` unchanged. A run with no
/// authorship data still splits: `polish` keeps the heading and replaces the
/// body with its no-data line, which is what the second document then carries.
/// Test: `split_tests::{splits_the_authorship_section,
/// no_authorship_heading_leaves_the_document_whole,
/// a_fenced_heading_line_is_not_split_on,
/// a_trailing_authorship_section_splits_to_the_end}`.
pub fn split_authorship(rendered: &str) -> (String, Option<String>) {
    let mut kept: Vec<&str> = Vec::new();
    let mut section: Vec<&str> = Vec::new();
    let mut in_fence = false;
    let mut in_section = false;

    for line in rendered.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim_start().starts_with("```") {
            in_fence = !in_fence;
        } else if !in_fence && let Some(text) = trimmed.strip_prefix("## ") {
            in_section = text.contains(AUTHORSHIP_HEADING_NEEDLE);
        }
        if in_section {
            section.push(line);
        } else {
            kept.push(line);
        }
    }

    if section.is_empty() {
        return (rendered.to_string(), None);
    }
    (rejoin(&kept, rendered), Some(rejoin(&section, rendered)))
}

/// Rejoin split lines, restoring the source's trailing newline.
///
/// Why: `str::lines` drops the final newline, and a markdown file that stops
/// mid-line reads as truncated to every downstream tool.
fn rejoin(lines: &[&str], source: &str) -> String {
    let mut out = lines.join("\n");
    if source.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Wrap an extracted authorship section as a standalone document.
///
/// Why: the section alone has no title, no date, and no key to the provenance
/// markers its own table cells carry — everything a reader needs travelled in
/// the code-review document's header. This adds exactly that much back and
/// nothing else.
/// What: promotes the section's `## ` heading to the document's `# ` title,
/// suffixed with the report codename, then the provenance legend, a line naming
/// the companion report and the generation date, the authorship-load gaps from
/// `gaps`, and the section body verbatim.
///
/// The gap lines are what keeps an authorship-leg failure legible on its own.
/// `polish` collapses a section with no data to `_No data available — see Gaps &
/// Caveats._`, and since #6046 that referenced section renders in the OTHER
/// document — so a reader holding only this one saw the collapse line and no
/// reason for it. Restating the repository's own gap lines here costs nothing
/// when the leg succeeded (`gaps` carries none) and is the whole explanation
/// when it failed.
/// Test: `split_tests::{authorship_document_carries_title_and_legend,
/// authorship_document_keeps_the_section_body,
/// authorship_document_states_its_own_data_gaps,
/// authorship_document_omits_the_gap_block_when_the_leg_succeeded}`.
pub fn authorship_document(
    title: &str,
    generated_date: &str,
    section: &str,
    gaps: &[String],
) -> String {
    let mut lines = section.lines();
    let heading = lines
        .next()
        .and_then(|l| l.trim_end().strip_prefix("## "))
        .map(str::trim)
        .unwrap_or("Authorship & Key-Person Risk")
        .to_string();
    let body = lines.collect::<Vec<_>>().join("\n");

    format!(
        "# {heading}: {title}\n\n{legend}\n\nCompanion to the technical \
         due-diligence report for {title}; generated {generated_date}.\n\n{gaps}{body}\n",
        legend = provenance::LEGEND,
        gaps = gap_block(gaps),
        body = body.trim(),
    )
}

/// The authorship-load gap lines, as a leading block, or `""` when there are
/// none.
///
/// Why: only the authorship leg's own gaps belong here — the code-review
/// document keeps the full Gaps & Caveats list, and repeating an unrelated
/// scan or metrics gap in this document would misattribute it to authorship.
fn gap_block(gaps: &[String]) -> String {
    let mine: Vec<&String> = gaps
        .iter()
        .filter(|g| g.starts_with(AUTHORSHIP_GAP_PREFIX))
        .collect();
    if mine.is_empty() {
        return String::new();
    }
    let mut out = String::from("**Data gaps in this assessment:**\n\n");
    for gap in mine {
        out.push_str("- ");
        out.push_str(gap);
        out.push('\n');
    }
    out.push('\n');
    out
}

#[cfg(test)]
#[path = "split_tests.rs"]
mod tests;
